version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ management UI
    networks:
      - smart-campus-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

  vehicle-detector:
    build: 
      context: ./app/vehicle-detector
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  authorization-service:
    build: 
      context: ./app/authorization-service
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8002:8000"
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  logger-service:
    build: 
      context: ./app/logger-service
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8003:8000"
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  security-dashboard-service:
    build: 
      context: ./app/security-dashboard-service
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8004:8000"
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  course-enrollment:
    build: 
      context: ./app/course-enrollment
    environment:
      - RABBITMQ_HOST=rabbitmq
    ports:
      - "8005:8000"
    depends_on:
      - rabbitmq
    networks:
      - smart-campus-network

  # notifications-service: # Add the new notifications service
  #   build:
  #     context: ./app/notifications
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #   ports:
  #     - "8007:8000" # Map host port 8007 to container port 8000
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - smart-campus-network

  # attendance-service: # Add the new attendance service
  #   build:
  #     context: ./app/attendance
  #   environment:
  #     - RABBITMQ_HOST=rabbitmq
  #   ports:
  #     - "8006:8000" # Map host port 8006 to container port 4000
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - smart-campus-network



networks:
  smart-campus-network:
    driver: bridge