name: smart-campus-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.109.2
    - uvicorn==0.27.1
    - pydantic==2.6.1
    - python-dotenv==1.0.1